spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
  liquibase:
    changeLog: "classpath:db/db-change-log.yaml"